### ISSUE TITLE
Extra username prompt when entering challenge

### ISSUE THREAD

**Issue by bhank** [dlenski/openconnect#102]
I am connecting to a GlobalProtect VPN which uses challenge auth, and passing in my username with `--user`. I am prompted for it again before entering the challenge answer:
```
Please enter your username and password
Password:
Enter Synchronous Response:
Username: myusername
Challenge:
```
Could the challenge auth use the username passed on the command line?

**Comment by dlenski** [comment]
Yeah, this is annoying, isn't it? _One_ user told me that he/she has to use a _different_ username for the challenge prompt… but I'm not sure if that's accurate, because it's just _crazy_.

I just pushed a patch to fix this and reuse the username by making it a hidden field in the challenge form. Please test.

**Comment by bhank** [comment]
The patch worked; no more extra username prompt. Thanks!
