### ISSUE TITLE
Enable non-interactive challenge auth

### ISSUE THREAD

**Issue by bhank** [dlenski/openconnect#103]
When I log in to a GlobalProtect VPN which uses challenge auth, I can't use `--passwd-on-stdin` and pipe in my password, because doing that prevents me from typing in the challenge answer. So I have to manually type my password and then the challenge answer. (Also the username, which I have addressed separately in https://github.com/dlenski/openconnect/issues/102)

I would like to be able to specify the answer to the challenge on the command line. In my case, there is only a single challenge, so it could be implemented as just a new parameter along the lines of `--challenge-answer=1234`; if VPNs exist which have multiple challenges, it could get more complicated, though (especially if they are in a non-predictable order).

**Comment by dlenski** [comment]
> … it could be implemented as just a new parameter along the lines of `--challenge-answer=1234`; if VPNs exist which have multiple challenges, it could get more complicated, though (especially if they are in a non-predictable order).

Yes, this is part of a more general class of problems of identifying exactly which form fields are which, and populating their values automatically.

See @dwmw2's ideas here: http://lists.infradead.org/pipermail/openconnect-devel/2017-August/004450.html

That said…

1. If your 2FA response comes from a HTOP/TOTP/RSA token, or something else that `openconnect` _knows how to handle itself_ via `--token-mode`, use that.
2. If the 2FA response is otherwise knowable ahead-of-time, you can still use `--passwd-on-stdin` with challenge auth. You just have to pipe in *two* lines. `(echo MyPassword; echo $My2FA) | openconnect …`
3. If the 2FA response is a random value that gets delivered to you _after_ the initial password is entered successfully (:man_facepalming::man_facepalming::man_facepalming:), now you have to get ekstra speshul creative. This works for me:

```sh
(echo MyPassword; read -p "Challenge: " CHALLENGE; echo $CHALLENGE) | \
    openconnect --prot=gp -u username vpn.server.com
```

**Comment by bhank** [comment]
Thanks. I used option 2, and it is now running smoothly and non-interactively for me.
