### ISSUE TITLE
--servercert and redirect

### ISSUE THREAD

**Issue by sarnila** [dlenski/openconnect#128]
In my case openconnect-gp connects first to one server which redirects to an other. Those servers have different certs. If I give no '--servercert' the first server is not challenged and connects but second gives:

  To trust this server in future, perhaps add this to your command line:
      --servercert xyz

Now if I give the above the first server is challenged but since the cert is for the second it gives the above with

   --servercert abc

If I give that the first goes OK but second server fails

Is there a way to deal with both servers with some parameters, or is some new code needed?

I'm not sure if this situation is particular to gp or general openconnect issue.

**Comment by dlenski** [comment]
> … log …

Hmm… the gateway server is giving you a very… odd response here. If you're willing to send me the gateway server address privately via email, that'd help me understand how to support this case.

If not, please checkout the latest build of the `master` branch, which may more gracefully work around _at least part of_ what's causing the problem here.

> The first server connect authenticates with 'Duo' (with my phone). That lacking the second is bound to fail.
>
> So can't skip the first server.

You would be surprised, actually. The administrators who run these VPNs don't really understand how the protocol works, and it's quite likely that it's possible to bypass the 2FA by going straight to the gateway. :stuck_out_tongue_closed_eyes:

Another (temporary) solution is to extract the signing certificate from the first server, the portal. Use [`test-globalprotect-login.py`](https://github.com/dlenski/openconnect/blob/globalprotect/test-globalprotect-login.py) and run `test-globalprotect-login.py https://vpn-portal.company.com/global-protect/getconfig.esp`, and then extract the PEM-formatted `<root-ca>` bits, save that as `portal.pem`, and then run `openconnect --prot=gp --cafile=portal.pem --servercert FINGERPRINT_OF_PORTAL vpn-portal.company.com`. That will cause openconnect to trust the gateway certificates — which are signed by the portal's "CA" certificate.

> One way to fix the openconnect code would be to expand the --servercert option so that you can give a list e.g. in following way:

This will be somewhat tricky to implement in a way that might be approved for merging upstream. Adding a mechanism to make `openconnect` trust the certs sent by the portal as valid for the server may be easier.

**Comment by sarnila** [comment]
It may well be that they don't understand fully what they are doing. But the arrangement with two servers is intentional. As mentioned the first is there to authenticate the user with password and the Duo authentication system (it contacts my phone for final authentication). As I have understood (not 100% sure) the first server sends temporary authentication data to gateway server as well as to my end. Thus the first authentication is needed for the second.

So both servers must be connected. It would probably work OK if openconnect could be somehow instructed not to check the first server's cert only of the second.

Extracting the cert (to pem-file) did also work: no complaints about certs. But I would prefer not to use it (and the python script to get it). I'm setting things also for my coworkers (IT is of no help).

Did you mean that giving and checking the cert per server name might be easier approved for merging?

Unfortunately I'm not authorized to give the portal for your testing. You would need a passwd and our IT should approve your phone number for Duo application to work. They will not allow that.

Here is the log of a successful connection (without the pem-file):

`
[log.txt](https://github.com/dlenski/openconnect/files/2446106/log.txt)
`

**Comment by shaananc** [comment]
I'm now also getting a similar outcome... two servers and a "Unexpected 200 result from server" at the end.

**Comment by dlenski** [comment]
@shaananc wrote:

> I'm now also getting a similar outcome... two servers and a "Unexpected 200 result from server" at the end.

You're commenting on a long-obsolete repo (see README) about an issue that I address in the mainline OpenConnect repo several years ago. It's now possible to specify _multiple_ `--servercert` arguments to OpenConnect, ever since:
[OpenConnect MR!162](https://gitlab.com/openconnect/openconnect/-/merge_requests/162).
