### ISSUE TITLE
Small problem when used on Slackware 14.2

### ISSUE THREAD

**Issue by ggddaa** [dlenski/openconnect#165]
I tried it on Slackware 14.2. The compilation went just fine. Anyway when I run openconnect to test the connect to my global protect gateway, the Slackware dialog box for network configuration pops up waiting for inputs. If I just close this dialog box, the script goes ahead showing the message "Failed to connect ESP tunnel; using HTTPS instead" and after that everything works fine.
  
I assume this is because at a certain point the system command "netconfig" is ran locally. This command on Slackware distribution just opens an interactive dialog box to configure the network which obviously has nothing to do with VPN configuration. If I'm not wrong, that the same command on other linux distributions can be used to configure/check network interfaces (maybe you use it just to set or to check some tunnel interface parameter). If this is the case would it be possible to use "ifconfig" instead to ensure a good portability on Slackware as well?

Thanks a lot!

**Comment by dlenski** [comment]
First, you shouldn't be using the version of OpenConnect in this repository, as explained in the issue template and README. Everything here was long ago integrated into the upstream project: 
https://gitlab.com/openconnect/openconnect/

Secondly, this is a very confusing report…? After repeatedly reading it, I am unsure what is the “small problem” you are referring to.

Is it one of these two? :man_shrugging: 

> `Failed to connect ESP tunnel` 

Unless you show me `openconnect -vvvv --dump` logs showing otherwise, this is almost certainly due to a GP server that's not configured for ESP support. Nothing the client can do about it.

> I assume this is because at a certain point the system command "netconfig" is ran locally. This command on Slackware distribution just opens an interactive dialog box to configure the network which obviously has nothing to do with VPN configuration. 

The fact that `netconfig` is getting invoked has little to do with `openconnect` per se. Rather it is [invoked in the `vpnc-script`](https://gitlab.com/openconnect/vpnc-scripts/-/blob/master/vpnc-script#L138-140) which OpenConnect uses for its routing configuration.

This may be relevant: https://www.linuxquestions.org/questions/slackware-14/vpnc-on-slackware-14-2-is-bringing-up-network-configuration-dialog-each-time-4175595447/#post5646866

Contributions to the vpnc-script to improve its Slackware support would be welcome.

Is it

**Comment by dlenski** [comment]
MR to fix the Slackware issue: https://gitlab.com/openconnect/vpnc-scripts/-/merge_requests/7

**Comment by ggddaa** [comment]
Thanks for the fast reply and sorry to have been not so clear in describing the problem. 

The small problem I was referring to was just the fact that the Slackware network configuration utility pops up avoiding openconnect to complete the connection procedures (I have mentioned the other error message just to describe all the main steps involved).  

Your comment on vpnc-script was really clarifying!  Thanks for that and also to have addressed me to very relevant  linuxquestions link. I will use it to adapt vpnc-script to Slackware environment.

**Comment by ggddaa** [comment]
Great you already did it!  Thank you once more!!
