### ISSUE TITLE
Helping installing openconnect 8.0

### ISSUE THREAD

**Issue by edgarcaldeira** [dlenski/openconnect#167]
Hey dlenski, thanks you for the previous help. I'm complete new to this world.

I did all the steps you send to me, just need quick advice on this part:

root@edgar-linux:~# git clone https://github.com/dlenski/openconnect.git
Cloning into 'openconnect'...
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 17615 (delta 0), reused 2 (delta 0), pack-reused 17613
Receiving objects: 100% (17615/17615), 9.84 MiB | 4.27 MiB/s, done.
Resolving deltas: 100% (13768/13768), done.
[1]+  Done                    $PANGPA start
root@edgar-linux:~# cd openconnect/
root@edgar-linux:~/openconnect# ls
README.md
root@edgar-linux:~/openconnect# 

Not suppose to have
$ ./autogen.sh
$ ./configure

Inside the folder?

Sorry to bother and thank you for all your help !

**Comment by dlenski** [comment]
Maybe I need to explain this better in the README. :grimacing: 

* No one **should be building anything from this repository**.
* No one should be using the contents of this repository for anything.
* I specifically _removed_ everything from this repository so that no one would get this far. :face_with_head_bandage:
* The only reason this repository still exists is because of the issue tracking for a few long-running complex issues, which I don't really want to lose.

Instead, you want to be using the upstream repository, https://gitlab.com/openconnect/openconnect.
… and you'll find build instructions for it here: https://www.infradead.org/openconnect/building.html
