### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by Davegb** [dlenski/openconnect#171]
I'm trying to build 8.10 version on Windows because the GUI version has 7.08. Downloaded the source files and tried to compile it with mingw-w64 with `mingw32-make Makefile.in`, but it throws "mingw32-make: Nothing to be done for 'Makefile.in'". Looked up this error and people said I had to clean it first, so I ran `mingw32-make clean`, but it throws "mingw32-make: *** No rule to make target 'clean'.  Stop.", so I tried with `mingw32-make -f Makefile.in clean`, which throws "Makefile.in:15: *** missing separator.  Stop.", so I ran out of ideas, since line 15 is `@SET_MAKE@`.

**Comment by dlenski** [comment]
1. You should report this upstream (https://gitlab.com/openconnect/openconnect/issues), since this repo is now obsolete and fully merged. [Potentially-related mingw build issue upstream](https://gitlab.com/openconnect/openconnect/-/issues/90).

2. You should *not* be building from `Makefile.in`. It is not a valid `Makefile`. Did you run `./autogen.sh` per [the build instructions](https://www.infradead.org/openconnect/building.html)?
