### ISSUE TITLE
Thank you for making this

### ISSUE THREAD

**Issue by howdoicomputer** [dlenski/openconnect#2]
Kind of an unusual issue to make but...

Thank you for making this. Without this fork, I wouldn't be able to use Linux at work. I am deeply appreciative of it existing.

**Comment by dlenski** [comment]
> Thank you for making this. Without this fork, I wouldn't be able to use Linux at work. I am deeply appreciative of it existing.

I'm very glad to hear it, @howdoicomputer. That's why I made it too…

As long as I've got your attention, I have a couple questions about how well it's working for you. These are a couple parts of the GlobalProtect protocol where I'm not 100% sure that I understand how it's supposed to work.

1. When you connect, does openconnect print `ESP session established with server` … or does it show `Set up DTLS failed; using SSL instead`? ESP has less overhead and better performance than SSL, and it works for me, but it's tricky to setup correctly, so it'd be good to know if it's working for you!

2. If you add `--dump` to the command line, it should show a big blob of XML configuration during the connection process, containing something like `<mtu>0</mtu>`. Does it show zero for you? Or does it show something non-zero? The correct MTU value is needed to reliably and efficiently send traffic between a client and a VPN tunnel, but GlobalProtect doesn't seem to provide any help figuring it out… at least on the VPN I have access to.

**Comment by howdoicomputer** [comment]
I'd be happy to help you!

Yeah, I do get a `Set up DTLS failed; using SSL instead` even if I compiled it with GnuTLS support. I have noticed that performance is a bit shaky and degrades over time - eventually requiring me to restart the VPN. Nothing mosh can't help out with.

I do in fact get a 0 value for mtu.

As far as usage, I wrote a wrapper shell script that feeds openconnect my credentials. I then wrote a systemd unit file that can stop and start openconnect via that wrapper. I *then* installed a Gnome Shell extension that allows me to start and stop systemd services using a drop down menu. I *theeeeeeen* wrote a custom Gnome Shell extension that shows whether or not my VPN is active.

So it more or less works like how it should work on a Mac/Windows machine.

**Comment by dlenski** [comment]
> Yeah, I do get a `Set up DTLS failed; using SSL instead` even if I compiled it with GnuTLS support.

Yeah, there is definitely something that I don't understand about how ESP is supposed to work for GlobalProtect VPNs other than mine. 

If you could connect with `--dump` and capture the big XML blob which is returned in response to `POST /ssl-vpn/getconfig.esp`, that would help a lot. 

This blob contains a whole bunch of potentially sensitive information: your username (but not password or authentication cookie), the VPN gateway, and the internal routing of the network you're connecting to. Probably the first step would be to [compare its structure to this anonymized version which I posted](https://gist.github.com/dlenski/5046e5f934ac111e8d8718fc10c25703#response-2) and tell me if anything looks different.

Second, if you could connect with `-vvvv` and tell me the ESP-related messages that you see. Here's what I get when establishing a successful ESP connection:

```
...
No MTU received. Calculated 1410
Parameters for incoming ESP: SPI 0x****
ESP encryption type AES-128-CBC (RFC3602) key 0x****
ESP authentication type HMAC-SHA-1-96 (RFC2404) key 0x****
Parameters for outgoing ESP: SPI 0x****
ESP encryption type AES-128-CBC (RFC3602) key 0x****
ESP authentication type HMAC-SHA-1-96 (RFC2404) key 0x****
Send ESP probes
Connected as 10.18.194.113, using SSL
Continuing in background; pid 26428
Received ESP packet of 84 bytes
ESP session established with server
Received ESP packet of 84 bytes
Received ESP packet of 84 bytes
ESP tunnel connected; exiting GPST mainloop.
```

> I have noticed that performance is a bit shaky and degrades over time - eventually requiring me to restart the VPN. Nothing mosh can't help out with.

That's a bit worrisome. I actually haven't noticed any problems with the SSL connection. Mine will stay connected for about an hour, until the server drops it due to inactivity (at which openconnect closes the connection and cleans up the `tun` device and exits).

**Comment by howdoicomputer** [comment]
Does this help?

```
HTTP body length:  (1827)
<
<       <response status="success">
<               <need-tunnel>yes</need-tunnel>
<               <ssl-tunnel-url>/ssl-tunnel-connect.sslvpn</ssl-tunnel-url>
<               <portal>GP_Gateway-N</portal>
<               <user></user>
<               <lifetime>57593</lifetime>
<               <timeout>7200</timeout>
<               <disconnect-on-idle>10800</disconnect-on-idle>
<               <bw-c2s>1000</bw-c2s>
<               <bw-s2c>1000</bw-s2c>
<               <gw-address></gw-address>
<               <ip-address></ip-address>
<               <netmask>255.255.255.255</netmask>
<               <dns>
<               </dns>
<               <wins>
<               </wins>
<               <mtu>0</mtu>
<               <dns-suffix>
<               </dns-suffix>
<               <access-routes>
<                       <member>0.0.0.0/0</member>
<               </access-routes>
<               <ipsec>
<                       <udp-port>4501</udp-port>
<                       <ipsec-mode>esp-tunnel</ipsec-mode>
<                       <enc-algo>aes128</enc-algo>
<                       <hmac-algo>sha1</hmac-algo>
<                       <c2s-spi>0x5B1B67F8</c2s-spi>
<                       <s2c-spi>0x1BFB360C</s2c-spi>
<                       <akey-s2c>
<                               <bits>160</bits>
<                               <val>foo</val>
<                       </akey-s2c>
<                       <ekey-s2c>
<                               <bits>128</bits>
<                               <val>bar</val>
<                       </ekey-s2c>
<                       <akey-c2s>
<                               <bits>160</bits>
<                               <val>foo</val>
<                       </akey-c2s>
<                       <ekey-c2s>
<                               <bits>128</bits>
<                               <val>bar</val>
<                       </ekey-c2s>
<               </ipsec>
<       </response>
Failed to setup ESP keys.
```

```
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Content-Type: application/xml; charset=UTF-8
Expires: Thu, 19 Nov 1981 08:52:00 GMT
X-FRAME-OPTIONS: DENY
HTTP body length:  (1827)
Failed to setup ESP keys.
TCP_INFO rcv mss 1460, snd mss 1460, adv mss 1460, pmtu 1500
No MTU received. Calculated 1410
Connecting to GPST tunnel over HTTPS...
Set up DTLS failed; using SSL instead
Connected as 172.20.92.79, using SSL
Sending data packet of 48 bytes
No work to do; sleeping for 10000 ms...
Sending data packet of 66 bytes
```

**Comment by dlenski** [comment]
Aha! Perfect! From what I'm seeing here, it actually sees to be a very simple problem with your server describing the encryption algorithm with a slightly different label.

Your server says… `<enc-algo>aes128</enc-algo>` … where mine says `<enc-algo>aes-128-cbc</enc-algo>`.

I just pushed a commit to check for this possibility. Let me know if it makes a difference!

**Comment by howdoicomputer** [comment]
Sure! There is an AUR package that compiles openconnect and I've been modifying PKGBUILD to build from this repository. I'll recompile and see what happens.

**Comment by howdoicomputer** [comment]
`aes-128-cbc` is now used!

**Comment by dlenski** [comment]
Great! So you're actually getting an ESP connection now? :+1:

**Comment by howdoicomputer** [comment]
```
Send ESP probes
Connected as foobar, using SSL
Received ESP packet of 84 bytes
ESP session established with server
Received ESP packet of 84 bytes
Received ESP packet of 84 bytes
ESP tunnel connected; exiting GPST mainloop.
Sent ESP packet of 100 bytes
```

**Comment by dlenski** [comment]
Excellent. I can cross that one off my list of "things that might not quite work right yet". Hopefully the connection is faster and more reliable as well.

**Comment by howdoicomputer** [comment]
Sure! I'll see if I can get some log output next time my connection drops.

**Comment by dlenski** [comment]
Great! If you run openconnect with `--syslog -vvvv`, it'll spew the detailed logging info to your syslog without cluttering up the terminal window.

**Comment by howdoicomputer** [comment]
Ah, I run it as a systemd service so I don't worry about it. I have it incredibly streamlined.

```
/usr/bin/echo -n password | sudo /usr/bin/openconnect --protocol=gp -u username --passwd-on-stdinvpngate.shutterfly.com >/dev/null 2>&1
```

```
$ cat /usr/lib/systemd/system/vpn.service
[Unit]
Description=A service wrapper for a forked version of openconnect that supports the GlobalProtect protocol. See https://github.com/dlenski/openconnect.

[Service]
ExecStart=/opt/vpn/wrapper.sh

[Install]
WantedBy=multi-user.target
```

But good to know! I was thinking of just shooting the logs to a logfile but instead I'll use the syslog flag.

**Comment by howdoicomputer** [comment]
@dlenski Also, performance has been massively improved.

**Comment by dlenski** [comment]
Excellent. You've probably seen it before, but "TCP over TCP is a bad idea", which means that SSL-based tunnels can experience seriously degraded performance: http://sites.inka.de/bigred/devel/tcp-tcp.html

**Comment by Joseluismantilla** [comment]
I can't do login using the GP protocol.
I execute:
$ sudo openconnect --protocol=gp  -u user gateway.test.gov.co  --dump -vvvv

But I receive: 
Got HTTP response: HTTP/1.1 200 OK
Date: Mon, 21 May 2018 00:13:45 GMT
Server: PanWeb Server/ - 
ETag: "c201-441-54344c3f"
Content-Length: 87
Connection: keep-alive
Keep-Alive: timeout=30, max=18
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Content-Type: application/xml; charset=UTF-8
Expires: Thu, 19 Nov 1981 08:52:00 GMT
HTTP body length:  (87)
< 
< 	<response status="success">
< 		<hip-report-needed>no</hip-report-needed>
< 	</response>
Gateway says no HIP report submission is needed.
Parameters for incoming ESP: SPI 0x32b26b52
ESP encryption type AES-128-CBC (RFC3602) key 0xb62a585e269dab243706f5f25845beb7
ESP authentication type HMAC-SHA-1-96 (RFC2404) key 0x77bc8a7467bd1782889ddc3259cad0395739480b
Parameters for outgoing ESP: SPI 0x643c9cd0
ESP encryption type AES-128-CBC (RFC3602) key 0x8b8adb83c5b48c86785f27d0e5546526
ESP authentication type HMAC-SHA-1-96 (RFC2404) key 0x33a0c69f9c19e49ace744834cae7be410f4d6720
Send ESP probes
No work to do; sleeping for 5000 ms...
No work to do; sleeping for 5000 ms...
No work to do; sleeping for 5000 ms...
No work to do; sleeping for 5000 ms...
No work to do; sleeping for 5000 ms...
No work to do; sleeping for 4000 ms...
No work to do; sleeping for 4000 ms...
No work to do; sleeping for 4000 ms...
No work to do; sleeping for 4000 ms...

Some ideas ?

**Comment by dlenski** [comment]
@Joseluismantilla, please create a new issue rather than piggy-backing on this unrelated one, and **include the complete log** and OS and build information as requested in the issue template.

> Some ideas ?

The log you're showing is incomplete. Everything that's shown in this portion of the log indicates correct behavior. So I have no idea… and need more information to proceed. ¯\\\_(ツ)\_\/¯
