### ISSUE TITLE
only first domain gets into resolv.conf

### ISSUE THREAD

**Issue by bugfood** [dlenski/openconnect#40]
# Problem description

1. I ran openconnect-gp as follows: 
`/usr/local/src/dlenski-openconnect/openconnect --user example --passwd-on-stdin --dump-http-traffic vpn.example.com --protocol=gp --certificate=/path/to/cert.p12`
2. vpnc-script does not populate resolv.conf with more than the first search domain

# Operating system and openconnect-gp version

openconnect-gp version:

```
OpenConnect version v7.08-177-g7571630
Using OpenSSL. Features present: TPM (OpenSSL ENGINE not present), HOTP software token, TOTP software token, DTLS, ESP
Supported protocols: anyconnect (default), nc, gp

```

operating system

```
Linux corey 4.9.0-2-amd64 #1 SMP Debian 4.9.13-1 (2017-02-27) x86_64 GNU/Linux
```

# Notes

This is a bit more of a question than a bug report. I may be able to fix the bug, but I'm unsure of how to proceed. What appears to be happening is:

1. Domains get returned in the config:
```
< 		<dns-suffix>
< 			<member>example1.com</member>
< 			<member>example2.com</member>
< 			<member>example3.com</member>
< 			<member>example4.com</member>
< 		</dns-suffix> 
```
2. CISCO_DEF_DOMAIN only contains the first member.
```
CISCO_DEF_DOMAIN='example1.com'
```

3. ...so resolv.conf ends up like this:
```
#@VPNC_GENERATED@ -- this file is generated by vpnc
# and will be overwritten by vpnc
# as long as the above mark is intact
nameserver 10.1.2.3
search example1.com
```

I can see where this is happening in gpst.c:
```
416                 } else if (xmlnode_is_named(xml_node, "dns-suffix")) {
417                         for (ii=0, member = xml_node->children; member && ii<1; member=member->next)
418                                 if (!xmlnode_get_text(member, "member", &s)) {
419                                         vpninfo->ip_info.domain = add_option(vpninfo, "search", s);
420                                         ii++;
421                                 }       
422                 } else if (<other stuff...>)
```
That appears to be looking for only the first member named "member", whereas all of them need to be considered.

What I do not understand is how to fix this. I'm having trouble finding specifications for the vpnc-script environment variables. Can CISCO_DEF_DOMAIN have multiple space-separated entries? That worked for me with a different setup with vpnc, but I do not know if vpnc-script handles that by design or by accident. There's also CISCO_SPLIT_DNS, but vpnc-script does not even handle that currently, so I do not know if that should be used.

https://mail.gnome.org/archives/commits-list/2016-July/msg01002.html

Also, any changes as-is will effect the search parameter in CISCO_CSTP_OPTIONS, and I cannot even find how that is supposed to be used.

Can you please suggest how I should proceed?

Thanks,
Corey

**Comment by dlenski** [comment]
Hi @bugfood. First of all, this is just about the most detailed and thoughtful issue report that I've ever received, so thank you!

This was my oversight. I did not realize that recent `vpnc-script` implementations support multiple domains, so I didn't include support for this in the GP config-parser.'

It appears that the way to handle this properly with the current openconnect `script.c` is to build up a string buffer containing all of the domains separated by ` `, and then save _that_ as `vpninfo->ip_info.domain`.

(The `cstp_options` linked list is needed so that the strings it references can be freed properly on shutdown or disconnect, so as not to leak memory.)

If you want to take a crack at a pull request for it, please do. Otherwise I can write it.

**Comment by bugfood** [comment]
Thanks for your kind words, and, of course, thank you for maintaining this fork--you got a group of us at my workplace out of a bind.

I ended up looking into this more on Friday, and I mostly convinced myself that using CISCO_SPLIT_DNS (vpninfo->ip_info.split_dns) was the way to do it. In cstp.c:536, this gets built up as a linked list already. The only oddity is that the environment variable gets the list in the reverse order. So, I worked up a couple patches:

https://github.com/dlenski/openconnect/compare/globalprotect...bugfood:globalprotect

The first change reverses the order of populating CISCO_SPLIT_DNS so as to retain the original order; the second change ports the list-prepending behavior from cstp.c. Note that I do not know what to do with CISCO_CSTP_OPTIONS, so that gets the original behavior of only getting a single "search=" entry; if you know what the right thing to do for that is, I can try to work it in.

The companion to these changes is this one for vpnc-scripts:
https://github.com/bugfood/vpnc-scripts/commit/19b0357349f3cede6d93245d8373be4ef7239866

Does this seem like a good approach? Each change should be backward compatible, so older scripts will work with newer openconnect, and vice versa.

Thanks,
Corey

**Comment by dlenski** [comment]
>I ended up looking into this more on Friday, and I mostly convinced myself that using CISCO_SPLIT_DNS >(vpninfo->ip_info.split_dns) was the way to do it.

Okay. The only problem with this is that the [current standard version of `vpnc-script`](http://git.infradead.org/users/dwmw2/vpnc-scripts.git/blob/HEAD:/vpnc-script) does not handle `CISCO_SPLIT_DNS` at all… it is totally ignored.

>The companion to these changes is this one for vpnc-scripts:
>bugfood/vpnc-scripts@19b0357

… but this should take care of that. Great! :+1: 

>In cstp.c:536, this gets built up as a linked list already.
>The only oddity is that the environment variable gets the list in the reverse order. So, I worked up a couple
>patches:

Does having the split routes in reverse order have any negative effect??

If so, you may want to submit https://github.com/bugfood/openconnect/commit/900b547a0b534dcb61ad0908f68b71c7c0184f96
to the official openconnect mailing list since it will improve the behavior for all currently-supported protocols (Cisco AnyConnect and Juniper)… and not just for GlobalProtect.

> Note that I do not know what to do with CISCO_CSTP_OPTIONS, so that gets the original behavior of only getting a single "search=" entry; if you know what the right thing to do for that is, I can try to work it in.

The `cstp_options` linked list needs to contain an entry for every dynamically-allocated configuration string. I'll comment on your patch with a suggestion for how to fix it without leaking memory.

**Comment by bugfood** [comment]
> Does having the split routes in reverse order have any negative effect??

This depends on site-specific configuration. As an example, consider a service that has instances in each of three environments:
service.dev.example.com
service.stage.example.com
service.prod.example.com

A VPN administrator may set up a search path as such:
search prod.example.com. stage.example.com. dev.example.com.

This way, a user can go to each instance by entering in the FQDN, but if they just enter "service", they will default to prod.

In the case I am dealing with, the VPN administrator is setting up search domains in a specific order in globalprotect, and we want to preserve that order.

> If so, you may want to submit bugfood/openconnect@900b547 to the official openconnect mailing list since it will improve the behavior for all currently-supported protocols (Cisco AnyConnect and Juniper)… and not just for GlobalProtect.

Sure, I can do that.

> I'll comment on your bugfood/openconnect@b70fbd7 patch with a small suggestion for how to fix it.

Got it. Thanks. I have to work on other things for right now, but I'll try to swing back to work on this before too long.

-Corey

**Comment by dlenski** [comment]
This all makes sense and I look forward to seeing and using the improvements :+1:

**Comment by bugfood** [comment]
I submitted the domain-order patch to openconnect-devel, to start with.

-Corey

**Comment by bugfood** [comment]
I'm not getting much attention on openconnect-devel recently. Am I asking the wrong questions, or is David just too busy?

-Corey

**Comment by dlenski** [comment]
Hi @bugfood… you are asking the right questions. In my experience, David Woodhouse works on OC in fairly sporadic bursts (probably to prevent himself from getting utterly consumed with the project :joy:).

Looks like he's following up on a lot of things now… will chime in on `-devel` if I can help.

**Comment by bugfood** [comment]
Thanks; I can understand that.

I got a response from David this morning.

-Corey

**Comment by agners** [comment]
Note that if `--protocol=anyconnect` is used, Split DNS still might be relevant. Those domain names should not be search suffix, but be considered when choosing which DNS server to use to resolve a certain domain name. `systemd-resolved` at least can handle such domain names. The `openconnect` client passes the domains through `CISCO_SPLIT_DNS` to the vpnc script, but it did not pass them to `systemd-resolved`. I sent a merge request for that:
https://gitlab.com/openconnect/vpnc-scripts/merge_requests/3

Just wanted to leave this information here, since google brought me here while googling for this problem (probably since `CISCO_SPLIT_DNS` has been mentioned).

**Comment by bugfood** [comment]
@agners , thanks--I never did find time to swing back to working on this problem.

-Corey
