### ISSUE TITLE
minus1 check fails

### ISSUE THREAD

**Issue by kamazee** [dlenski/openconnect#50]
# Problem description

1. I ran openconnect-gp as follows: `openconnect --protocol=gp --dump -vvvv`
2. Connection failed:
```
GlobalProtect login returned authentication-source=All_AD_Users
GlobalProtect login returned minus1=6 (expected -1)
Failed to parse server response
Response was:<?xml version="1.0" encoding="utf-8"?><jnlp><application-desc><argument>(null)</argument><argument>hash1</argument><argument>hash2</argument><argument>GP-Gateway-Global-N</argument><argument>mylogin</argument><argument>AD_Group</argument><argument>vsys1</argument><argument>mycompany</argument><argument>(null)</argument><argument></argument><argument></argument><argument></argument><argument>tunnel</argument><argument>6</argument><argument>4100</argument><argument></argument><argument></argument><argument></argument><argument></argument></application-desc></jnlp>
```

# Operating system and openconnect-gp version

openconnect-gp version: latest from git

```
OpenConnect version v7.08-181-g8d98948
```

operating system

```
Linux xxx 4.12.4-1-ARCH #1 SMP PREEMPT Fri Jul 28 18:54:18 UTC 2017 x86_64 GNU/Linux
```

# GlobalProtect VPN information

(not sure it's relevant, will provide if needed)

***

Given the description above, I wonder what the meaning of "minus1" is. This check fails when I try to connect, and when I remove it and recompile openconnect, my connection works just fine. I guess that it's a bit of proprietary protocol the purpose of which is yet to be determined; however the assertion might be somewhat excessive.

**Comment by dlenski** [comment]
Thanks @kamazee for this report and the patch. As you can see in the source code, I have good ideas of what 10 of 16 `<argument>`s mean, and 5 always seem to be missing… but this 1 is a mystery to me. I added the checks specifically so that openconnect wouldn't silently ignore unexpected values, because that caused more confusion.

If you figure out how `6` is different from `-1`, do let me know.

When you run `openconnect --protocol=gp --dump`, does the getconfig XML show anything different or unexpected? Does it give you IPv6 routing information by any chance? (Just a wild guess.)
