### ISSUE TITLE
Use OpenConnect Without Specifying a Certificate

### ISSUE THREAD

**Issue by davidpgil** [dlenski/openconnect#60]
I use the GlobalProtect app on MacOS as my VPN and I never needed to use a certificate.pem file to use it. It seems like OpenConnect requires I have one? How do I get one?

Apologies if my questions are too rudimentary. I am trying to understand how to use your app so I can connect to my job remotely using my Ubuntu laptop.

Thanks in advance for any help you can provide.

**Comment by gsiciliano** [comment]
You can try to use the option --servercert with server's fingerprint.

If you run openconnect without certificate options (only with protocol=gp and server ip address), you obtain a message like:
```
Certificate from VPN server "serverhost" failed verification.
Reason: signer not found
To trust this server in future, perhaps add this to your command line:
    --servercert pin-sha256:serverfingerprint
Enter 'sì' to accept, 'no' to abort; anything else to view: 

```
I hope this may help you

**Comment by davidpgil** [comment]
I don't know how to get my jobs server fingerprint. How do I do that? I i use to connect to my jobs server is typing in a url and password just as "sslvpn.workurl.com" and "username" and my "password" there is no idication of needing to fingerprint or certify anything. Is there a way to use OpenConnect without needing a fingerprint?

Here is a graphic of the GlobalProtect GUI I use to enter my login info on MacOS:
![Graphic of the GlobalProtect GUI](https://user-images.githubusercontent.com/1891288/32159427-d4864442-bd90-11e7-867e-6bc0f93e8d3e.png)

**Comment by gsiciliano** [comment]
From UBUNTU, in a terminal type the command: 
`sudo openconnect --protocol=gp <hostaddress>`
then openconnect requests the username and password to access the vpn host.
When done, the message below is showed (in my ubuntu laptop worked fine..)
```
Certificate from VPN server "serverhost" failed verification.
Reason: signer not found
To trust this server in future, perhaps add this to your command line:
    --servercert pin-sha256:serverfingerprint
Enter 'sì' to accept, 'no' to abort; anything else to view: 
```
Recently I changed from windows to ubuntu and I've the same issue

**Comment by davidpgil** [comment]
Thank you. I will try this method at my next opportunity and update this thread with my result.

**Comment by dlenski** [comment]
@davidpgil, the ideal way to fix this is to convince your VPN administrator to generate a valid certificate signed by a well-known CA… but since the official GlobalProtect client can be configured not to require this (bad!) they probably won't care.

Here is how to get the server certificate fingerprint, as @gsiciliano suggested:

```sh
$ gnutls-cli --insecure globalprotect.gateway.server.com
Processed 178 CA certificate(s).
...
- Certificate[0] info:
... SHA-1 fingerprint `0deadbeef0deadbeef0deadbeef0deadbeef0deadbeef0deadbeef' ...
```

Assuming you consider save the certificate trustworthy despite not being authenticated by the CAs, copy the fingerprint and then run openconnect as follows in order to avoid the warning/error about unverifiable certificate:

```sh
openconnect --servercert 0deadbeef0deadbeef0deadbeef0deadbeef0deadbeef0deadbeef [usual arguments]
```

**Comment by davidpgil** [comment]
Thank you @gsiciliano and @dlenski  both of your answers helped me a great deal! I have a workign connection now with openconnect + remmina. I love you guys!

**Comment by davidpgil** [comment]
I'm new to how things are done with GitHub... Is this issue supposed to be closed? Do I close it? I consider the scope of the issue solved. Many thanks.

**Comment by chrishiestand** [comment]
With openconnect v7.08, in my environment, I had to modify this to prepend hash name:

```
openconnect --servercert=sha1:26cfbcdefg... [usual arguments]
# or
openconnect --servercert=sha256:a8cfbcdedeadbeefdeadbeeffg... [usual arguments]

```

**Comment by dlenski** [comment]
> With openconnect v7.08, in my environment, I had to modify this to prepend hash name:

@chrishiestand, that's a good point. openconnect v7.08 appears to *require* the prefix (whereas previous versions defaulted to `sha1:`, or didn't support `sha256:` at all).

This could be improved in the documentation. Since it's outside the scope of GP-specific changes, you may want to submit feedback or a patch on [the official mailing list](www.infradead.org/openconnect/mail.html).

**Comment by stefanct** [comment]
Instead of just getting the certificate's hash one can also save it into a file (and provide it to the nm GUI) via `gnutls-cli --insecure example.com --save-cert=example.pem`. That does not change the (in)security of the whole approach but what can you do... ;)

**Comment by ricardoroehe** [comment]
You could install the "untrusted" certificate manually on your machine. 

(In Linux Mint, you copy the PEM/CRT files to /usr/local/share/ca-certificates and run sudo update-ca-certificates. Just download the cert files through your browser to do that.)

**Comment by dlenski** [comment]
I'm going to lock this issue because it's not GP-specific, and not really even OpenConnect-specific… it's just a general purpose issue with untrusted server TLS certificates.

The upstream project (https://gitlab.com/openconnect/openconnect/) or mailing list (https://www.infradead.org/openconnect/mail.html) are better places for discussing OpenConnect's interface for handling server certificates.
